In [4]:
import numpy as np
import pandas as pd 
import operator as op
import math as mt 
import matplotlib_inline as plt 


In [5]:
df = pd.read_csv("head_brain_dataset.csv")
df

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

#### Extract X and Y values (Head Size and Brain Weight)

In [9]:
x = df["Head Size(cm^3)"].values
y = df["Brain Weight(grams)"].values

In [11]:
print(x)
print(y)

[4512 3738 4261 3777 4177]
[1530 1297 1335 1282 1590]


#### Step 3: Calculate the slope (m) and intercept (c)

In [12]:
# Mean of X and Y

x_mean = np.mean(x)
y_mean = np.mean(y)
print(x_mean)
print(y_mean)

4093.0
1406.8


In [13]:
sum_numerator = np.sum((x-x_mean)*(y-y_mean))
sum_denominator = np.sum((y-y_mean)**2)
print("Numerator",sum_numerator)
print("Denomenator", sum_denominator)

Numerator 133363.0
Denomenator 81526.8


In [14]:
m_slop = sum_numerator / sum_denominator
print("m-slop = " , m_slop)

m-slop =  1.635817915090498


##### Calculate c (Intercept)

In [15]:
c = y_mean - (m_slop * x_mean)
print("Intercept-c =" , c)

Intercept-c = -5288.602726465408


#### Step 4: Predict Y values using the formula y = mx + c


In [16]:
Y_pred = m_slop * x + c
print("Your predicted y is: ",Y_pred)


Your predicted y is:  [2092.20770642  826.08464014 1681.61740974  889.88153883 1544.20870487]


####  Calculate R-squared error

In [18]:
Y_pred

array([2092.20770642,  826.08464014, 1681.61740974,  889.88153883,
       1544.20870487])

In [19]:
df

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

#### Step 5: Calculate R-squared error
- its define accuracy

In [23]:
mean_sqr_error = np.sum((y - y_mean)**2) # mean square error

residual_sqr_error = np.sum((y-Y_pred)**2)

print(" The Mean Square Error is: ",mean_sqr_error)
print(" The Residual Square Error is: ",residual_sqr_error)

 The Mean Square Error is:  81526.8
 The Residual Square Error is:  813836.1403413588


In [24]:
R_sqr = 1 - (residual_sqr_error / mean_sqr_error)
print("The accuracyy of this model is: ",R_sqr)
Y_pred


The accuracyy of this model is:  -8.982436945168445


array([2092.20770642,  826.08464014, 1681.61740974,  889.88153883,
       1544.20870487])